apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-controller-manager
  ports:
    - name: metrics
      protocol: TCP
      port: 10252
      targetPort: 10252
